### ISSUE TITLE
Is there a way to have more than 6 modals in portfolio?

### ISSUE THREAD

**Issue by rubo-g** [IronSummitMedia/startbootstrap-freelancer#21]
first off love the template, does pretty much what I need. well, the title says it all - Is there a way to have more than 6 modals in portfolio? I am able to add images but adding 
"<div class="portfolio-modal modal fade....</div>" doesn't do anything, clicking on image #7 and on  brings modal 6. Tnx in advance!

Rubo-g

**Comment by rubo-g** [comment]
never mind, found it. it was easy.

**Comment by kelvinfann** [comment]
wait how did you do it without a weird offset? After I go to the 7th one it starts to right indent for some reason
So it looks something like this

```
[img1] [img2] [img3]
[img4] [img5] [img6]
[ N/A ] [ N/A ] [img7]        
```
