### ISSUE TITLE
Images Not Showing

### ISSUE THREAD

**Issue by rlist3r** [IronSummitMedia/startbootstrap-freelancer#29]
Hi everyone,

I'm having trouble with the StartBootstraps themes. It seems like whichever theme I download, the images do not show up when I upload the files to my host. Each time I attempt to open an image in a new tab, I get the following error message: 
Not Found
The requested URL /home/rlisterc/public_html/adaptive-images.php was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

The adaptive-images.php file is absolutely where it should be, so I am stumped. The site in its current form can be found at rayleenlister.ca and if anyone has any insight I would really appreciate it. Thanks!

**Comment by davidtmiller** [comment]
Make sure the file path is correct, I am not sure what the issue would be here though other than that. Hopefully you've found a solution!
