### ISSUE TITLE
Scrolling nav scrolls twice

### ISSUE THREAD

**Issue by n30r3b3l** [IronSummitMedia/startbootstrap-freelancer#52]
Hi. I love this theme, however I have a small issue that I cannot figure out. When I click on a link on the scrolling nav bar, it scrolls to that anchor twice. It will scroll to that section, then go back where you were on the page, then scroll to that section again. The website is at www.westberryautotransport.com. Can you please help me with this issue.

**Comment by wustep** [comment]
The trigger is happening twice, maybe due to some of the other js you've added?
Here's a workaround (credit to [gajotres](http://www.gajotres.net/prevent-jquery-multiple-event-triggering/)): 

# freelancer.js

```javascript
// jQuery for page scrolling feature - requires jQuery Easing plugin
$(function() {	
    $('body').on('click', '.page-scroll a', function(event) {
    	$(this).off('click', '.page-scroll a', function(event) {
			var $anchor = $(this);
			$('html, body').stop().animate({
				scrollTop: $($anchor.attr('href')).offset().top
			}, 1500, 'easeInOutExpo');
			event.preventDefault();
    	});
    });
});
```

Hope this helps,
Stephen

**Comment by n30r3b3l** [comment]
Thank you very much for your help. That workaround fixed the issue. Now I guess I just need to dig through the rest of my JS and find out what caused that to happen.
